/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Material } from "./Material";
import { MaterialCountArgs } from "./MaterialCountArgs";
import { MaterialFindManyArgs } from "./MaterialFindManyArgs";
import { MaterialFindUniqueArgs } from "./MaterialFindUniqueArgs";
import { DeleteMaterialArgs } from "./DeleteMaterialArgs";
import { MaterialService } from "../material.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Material)
export class MaterialResolverBase {
  constructor(
    protected readonly service: MaterialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "any",
  })
  async _materialsMeta(
    @graphql.Args() args: MaterialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Material])
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "any",
  })
  async materials(
    @graphql.Args() args: MaterialFindManyArgs
  ): Promise<Material[]> {
    return this.service.materials(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Material, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "read",
    possession: "own",
  })
  async material(
    @graphql.Args() args: MaterialFindUniqueArgs
  ): Promise<Material | null> {
    const result = await this.service.material(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Material)
  @nestAccessControl.UseRoles({
    resource: "Material",
    action: "delete",
    possession: "any",
  })
  async deleteMaterial(
    @graphql.Args() args: DeleteMaterialArgs
  ): Promise<Material | null> {
    try {
      return await this.service.deleteMaterial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
